{"metadata":{"usedHelpers":[],"marked":[],"modules":{"imports":[],"exports":{"exported":[],"specifiers":[]}}},"options":{"filename":"/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js","filenameRelative":"/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js","env":{},"retainLines":false,"highlightCode":true,"suppressDeprecationMessages":false,"presets":[],"plugins":[[[],{"polyfill":false}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],{"loose":true}],[[],{"loose":true}],[[],null],[[],{"loose":true}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],{"loose":true}],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null],[[],null]],"ignore":[],"code":true,"metadata":true,"ast":false,"comments":true,"compact":false,"minified":false,"sourceMap":true,"sourceMaps":true,"sourceMapTarget":"/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js.map","sourceFileName":"/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js","babelrc":false,"sourceType":"module","moduleIds":false,"passPerPreset":false,"basename":"multiple.done"},"ignored":false,"code":"// The suite below should result in an additional error, but does\n// not. Uncomment once this bug is resolved.\n\n// describe('suite', function() {\n//   beforeEach(function(done) {\n//     done();\n//     done();\n//   });\n\n//   it('test', function() {});\n// });\n\nit('should fail in a test-case', function (done) {\n  process.nextTick(function () {\n    done();\n    done();\n  });\n});","ast":null,"map":{"version":3,"sources":["/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js"],"names":[],"mappings":";;;;;;;;;;;;AAYA,GAAG,4BAAH,EAAiC,UAAS,IAAT,EAAe;AAC9C,UAAQ,QAAR,CAAiB,YAAU;AACzB;AACA;AACD,GAHD;AAID,CALD","file":"/packages/practicalmeteor:mocha/test/integration/fixtures/multiple.done.js.map","sourcesContent":["// The suite below should result in an additional error, but does\n// not. Uncomment once this bug is resolved.\n\n// describe('suite', function() {\n//   beforeEach(function(done) {\n//     done();\n//     done();\n//   });\n\n//   it('test', function() {});\n// });\n\nit('should fail in a test-case', function(done) {\n  process.nextTick(function(){\n    done();\n    done();\n  });\n});\n"]},"hash":"a974577ba5d784cfb13b41ebef1d765e09361833"}
